# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170522_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
