# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170522_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='Customer', max_length=20),
        ),
    ]
