# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='/media/products/no_image.jpg', max_length=500, null=True, upload_to=b''),
        ),
    ]
