# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170531_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='/media/products/no_image.jpg', null=True, upload_to='/media/products/'),
        ),
    ]
