# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170531_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='/media/products/no_image.jpg', upload_to='/media/products/'),
        ),
    ]
