# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170531_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='/media/products/no_image.jpg', upload_to=b''),
        ),
    ]
